### ISSUE TITLE
100% code coverage

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp-skel#16]
We should get this repo to 100% coverage such that forks that don't start by adding coverage will explicitly decline/fail.

We need only very minor tests to get 100% coverage: https://codecov.io/gh/mapbox/node-cpp-skel/src/e44926c432cf2ee0c809a29da52541b0e0d35b38/src/hello_world.cpp

**Comment by GretaCB** [comment]
@gretacb and @springmeyer to finish this off. Looking at [hello-world.cpp](https://codecov.io/gh/mapbox/node-cpp-skel/src/dcd6e49faff2a851164c1357a7af2cc6f3ddea78/src/hello_world.cpp
). Would allow future devs using skel to see their code coverage decrease as they add their own code.

**Comment by GretaCB** [comment]
@springmeyer Working off branch here https://github.com/mapbox/node-cpp-skel/tree/coverage

**Comment by GretaCB** [comment]
✅  per https://github.com/mapbox/node-cpp-skel/pull/28. Closing!

**Comment by springmeyer** [comment]
Great work @GretaCB. I'll now update the README to point to https://github.com/mapbox/cpp#code-coverage for more details on how this works.
