### ISSUE TITLE
Example code for async function

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp-skel#2]
Most users of this repo are going to be building node C++ modules because they want to leverage the C++ threadpool (https://2015.foss4g-na.org/session/geodata-processing-nodejs) for writing async functions.

We should extend the `HelloWorld` class to expose a simple async function.

Some references:

  - Most sophisticated, fully Nan way to do this: https://github.com/Project-OSRM/node-osrm/pull/193
  - Simplest example from node-mapnik (which does not use Nan, but more direct libuv): https://github.com/mapnik/node-mapnik/blob/a91e322e60a7e9911a69f39e025570993def6960/src/mapnik_image_view.cpp#L437-L551

**Comment by mapsam** [comment]
Working over in https://github.com/mapbox/node-cpp-skel/pull/3

**Comment by springmeyer** [comment]
closing, will track at #3

**Comment by springmeyer** [comment]
Actually, going to re-open, digest https://github.com/Project-OSRM/node-osrm/pull/193#issuecomment-227101937, and then will share next actions on improvements to #3 here, when I have them.

**Comment by springmeyer** [comment]
Tracking at #5 works, closing.
