### ISSUE TITLE
Move to `language:node_js`?

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp-skel#32]
Long ago `language:node_js` was broken on travis OS X machines. And often travis linux machines used nvm but a broken or old version. So we started consistently:
- installing our own nvm to support installing node consistently on os x (avoids need for brew)
- using `language:generic` since these machines boot fastest

Now I think `language:node_js` might actually work on travis OS X machines. So we could try testing using `language:node_js` again to avoid having to depend on nvm when creating matrix builds for lots of different node_js versions.

/cc @mapsam

**Comment by springmeyer** [comment]
TODO:

  - ensure that `language:node_js` does not boot way slower (> 30s) than `language:generic`
  - ensure `node_js` works on OS X and the version is preferred above whatever is on the system by default via the travis homebrew environ (make sure it does not conflict in weird ways)

**Comment by mapsam** [comment]
Started working on this in #26

**Comment by mapsam** [comment]
@springmeyer got some consistent times here:

type|time|build
---|---|---
Installing node manually | ~2m 30s | [build](https://travis-ci.org/mapbox/node-cpp-skel/builds/167194988)
Using TravisCI `node_js` | ~3m 20 | [build](https://travis-ci.org/mapbox/node-cpp-skel/builds/167186604)

Seems like it's best to stick to installing node ourselves, for now.

**Comment by springmeyer** [comment]
Oh my, that is bad. Thanks for testing @mapsam. I wonder why `node_js` is so much slower... On first glance the stuff that node_js machines run (visible at https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/node_js.rb) looks pretty similiar to what we do manually: install nvm, install node... Hrm

**Comment by mapsam** [comment]
@springmeyer pull the trigger on this in #36 - closing!

**Comment by springmeyer** [comment]
Thanks for closing @mapsam - I meant to followup on this issue. I've seem build times that match recently and also feel that `node_js` is just the right way to go given how convenient it is (and helps keep .travis files concise).

**Comment by mapsam** [comment]
Totally agreed @springmeyer - in this case simplicity wins over performance
