### ISSUE TITLE
Remove documentation.js dependency?

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#49]
The documentation.js dependency is very large ~116.5 MB when installed. I think we should remove this dependency from being installed automatically and only install it within the `npm run docs` script itself. 

Would look like this:

```
"docs": "npm install documentation && documentation build src/*.cpp src/standalone_async/*.cpp src/standalone/*.cpp --polyglot -f md -o API.md"
```

cc @springmeyer @GretaCB

**Comment by GretaCB** [comment]
hey @mapsam , your example above is what the skel _used_ to have before last week. Also, per chat last week, we discovered that the skel didnt have documentation.js as a dep in package.json.

I've since added this step as part of the docs https://github.com/mapbox/node-cpp-skel#installation.

**Comment by mapsam** [comment]
`:facepalm:` 

Sorry @GretaCB totally blanked. I'm working on the `cf` branch which hasn't been updated with master in a while. Please disregard!
