### ISSUE TITLE
Proper handling of callbacks with Nan

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#5]
Diving into #4 led me to checking our usage of `Nan::MakeCallback`, which led me to a few more tickets out in the wild about how it might not be the best thing in the world. Can we improve on [our current usage](https://github.com/mapbox/node-cpp-skel/pull/3/files#diff-3edf373e7d337dd35daf38c5032ac0b6R180)?

refs:
- https://github.com/nodejs/nan/issues/284
- change to node-osmium callbacks that we can learn from: https://github.com/osmcode/node-osmium/commit/572fd278f0351557f97bc17f152cee210635c1ba
- https://github.com/mapbox/mapbox-gl-native/commit/706f0f2682ae859092a0c7e084b993f7b478c84c
- https://github.com/Project-OSRM/node-osrm/pull/193#issuecomment-227101937
- https://github.com/nodejs/nan/issues/548

cc @springmeyer @camilleanne @GretaCB

**Comment by GretaCB** [comment]
#### How can we consistify?
- We might be using different versions of Nan across modules
- We might be handling callback differently across modules
- Handle callbacks instead of throwing (node-mapnik)
- Return the error in the callback when doing validation whenever possible (node-mapnik)

**Comment by springmeyer** [comment]
I re-read the original post linked above (https://github.com/nodejs/nan/issues/284) and my conclusion is that we don't need to make any changes. The issue raised at https://github.com/nodejs/nan/issues/284 is solvable by new APIs in nan to call callbacks directly, but does not apply to our usecase. The post says:

> This form (MakeCallback) is intended only for use by C++ code that was dispatched from the libuv event loop, and not for C++ code that was invoked from JS code.

In the case of node-cpp-skel we are only doing the former: calling a callback after returning from the libuv event loop.
