### ISSUE TITLE
Best practices around publishing dev releases

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#59]
Would be great to get a note in the /docs/publishing-binaries.md file about how to best publish dev releases of node-cpp-addons before tagging and publishing formal releases!

cc @GretaCB @springmeyer

**Comment by springmeyer** [comment]
Taking a crack at starting this doc:

### Dev releases

You may want to test your module works correctly, in downstream dependencies, before formally publishing. To do this we recommend you:

1. Create a branch of your node c++ module

1. Modify the `version` string in your `package.json` like:

```diff
diff --git a/package.json b/package.json
index e00b7b5..22f7cd9 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "@mapbox/node-cpp-skel",
-  "version": "0.1.0",
+  "version": "0.1.0-alpha1",
   "description": "Skeleton for bindings to C++ libraries for Node.js using NAN",
   "url": "http://github.com/mapbox/node-cpp-skel",
   "main": "./lib/index.js",
```

1. Publishing C++ binaries by pushing a commit with `[publish binary]` per https://github.com/mapbox/node-cpp-skel/blob/master/docs/publishing-binaries.md#7-all-done

1. Require your module in downstream applications like:

```js
"your-module": "https://github.com/<your-org>/<your-module>/tarball/<your-branch>",
```

**Comment by springmeyer** [comment]
I'll add that the above process is fairly manual. Others have been thinking about whether this could be automated - e.g. what if nightly builds where published and available to be pulled in. /cc @danpat (node-osrm) and @mollymerp (node-mapbox-gl-native) have both been thinking about this a bit with @springmeyer but we've not attempted an implementation yet.

**Comment by GretaCB** [comment]
First iteration merged over at https://github.com/mapbox/node-cpp-skel/pull/92

**Comment by springmeyer** [comment]
done in #115
