### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#7]
I really like how this helper repo sets up CI, tests, & other features so we can start running quickly. It seems worth adding documentation.js into the mix, including JSDoc comments so we can generate API docs quickly. I'm thinking nothing more than using the Markdown output (as opposed to full HTML pages). What do you think @springmeyer @GretaCB?

**Comment by GretaCB** [comment]
@mapsam love it. Continue with [this format](https://github.com/mapbox/node-cpp-skel/pull/3/files#diff-3edf373e7d337dd35daf38c5032ac0b6R61)?

**Comment by mapsam** [comment]
@GretaCB great! I'll add a devDependency for documentation.js and a script that generates an `API.md` into the root level of the repository.

**Comment by mapsam** [comment]
completed in f17066be37f51d4135ea6f87c25e8a33bfec9114
