### ISSUE TITLE
Docs on clang-tidy

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-cpp-skel#70]
Add docs to the extended section on:

 - What is clang-tidy?
 - What kind of bugs does it catch?
 - How to run it locally: `make tidy`
 - When you see a failure, what do you do? (hint: clang-tidy outputs shorthand codes for each error/warning that can be googled to get to its individual page like https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-copy-initialization.html)
 - Add note that when forward porting node-cpp-skel to another existing node c++ addon, it is expected that you will hit clang-tidy errors. Fixing them can take some time, so some devs may wish to disable the travis job to be able to triage slowly.

Context: clang-tidy support landed in #64

**Comment by GretaCB** [comment]
PR going over at https://github.com/mapbox/node-cpp-skel/pull/103
