### ISSUE TITLE
mason command not found in clang-tidy.sh

### ISSUE THREAD

**Issue by mapsam** [mapbox/node-cpp-skel#72]
I'm using .travis file over at mbtiles-geostats and hit the following [error message on travis](https://travis-ci.org/mapbox/mbtiles-geostats/jobs/269313707) for the clang-tidy build:

```
$ make tidy
./scripts/clang-tidy.sh
./scripts/clang-tidy.sh: line 22: mason: command not found
make: *** [tidy] Error 127
```

Looks like mason isn't setup, because we skip [this conditional](https://github.com/mapbox/node-cpp-skel/blob/master/scripts/clang-tidy.sh#L9). 

cc @GretaCB

**Comment by springmeyer** [comment]
Thanks for catching this glitch! It is the same as #71 in that we need to add to the `.gitignore`. The `local.env` should not be committed to git, so removing https://github.com/mapbox/mbtiles-geostats/blob/master/local.env will fix this.

**Comment by springmeyer** [comment]
Solved by https://github.com/mapbox/node-cpp-skel/commit/34b915a8480cd00ffca0313d12ad951fb13565e4

**Comment by springmeyer** [comment]
@mapsam - fix also ported to https://github.com/mapbox/mbtiles-geostats/pull/10 for ya.
